# SPDX-License-Identifier: GPL-3.0-or-later
---
# handlers file for image_builder

- name: Restart composer
  ansible.builtin.service:
    name: osbuild-composer
    state: restarted

- name: Load blueprint
  ansible.builtin.command:
    cmd: >
      composer-cli
      blueprints
      push {{ __target_dir }}/{{ ib_name }}.toml
  changed_when: true
  vars:
    __target_dir: "{{ ansible_user_dir }}/{{ ib_blueprint_dir }}/{{ ib_name }}_{{ ib_image_version }}"
