# SPDX-License-Identifier: GPL-3.0-or-later
---
# handlers file for image_builder

- name: Restart composer
  ansible.builtin.service:
    name: osbuild-composer
    state: restarted

- name: Load the blueprint
  ansible.builtin.command:
    cmd: >
      composer-cli
      blueprints
      push {{ __ib_bp_full_path }}
  changed_when: true
  listen: Load blueprint

- name: Define overwrite variable
  ansible.builtin.set_fact:
    __overwrite_img: true
  listen: Load blueprint
