# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for image_builder/tasks/01_deploy_blueprints.yml

- name: Blueprint is present
  ansible.builtin.template:
    src: blueprint.toml.j2
    dest: "{{ __ib_bp_full_path }}"
    mode: "0644"
    owner: "{{ ib_user }}"
    group: "{{ ib_user }}"
  when: "ib_name != 'custom-image'"
  notify: Load blueprint

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
